### ISSUE TITLE
Mechanism for tester to define the .as_tester_char() mapping?

### ISSUE THREAD

**Issue by pderouen** [Origen-SDK/o2#105]
Is there already a plan for providing a way for the tester to set the mapping from pin action to vector character? The pin state tracker <code>.as_strings()</code> method calls the pin actions <code>.as_tester_char()</code> method which has a fixed mapping.

https://github.com/Origen-SDK/o2/blob/5d443d7552d71c7438a9cfc9e3513afc627db65c/rust/origen/src/core/model/pins.rs#L741

https://github.com/Origen-SDK/o2/blob/5d443d7552d71c7438a9cfc9e3513afc627db65c/rust/origen/src/core/model/pins/pin.rs#L51

**Comment by coreyeng** [comment]
Yes. A lot of the currently hard-coded stuff was just to get the pattern renderer off the ground. The `to_string` of the pin states shouldn't be used for anything more than debug long term, or to provide a base starting point. Ideally, the pin state rendering would be in the [tester trait](https://github.com/Origen-SDK/o2/blob/master/rust/origen/src/core/tester.rs#L342-L356). For only supporting V93K though, going that far wasn't needed just yet. Actually though, not even correct for the 93K, since it allows remapping characters to whatever, but like it said, it was sufficient for getting it off the ground.

I do plan to do this but not sure when I'd get to it. If you want to take this, just add it to the [project](https://github.com/Origen-SDK/o2/projects/3). Otherwise I'll get to it when I get back to pattern generation.

**Comment by pderouen** [comment]
I am working on uflex pattern generation. I can take the task of adding a mapper method to the api trait.
