### ISSUE TITLE
Pin group creation with N args of varying types

### ISSUE THREAD

**Issue by info-rchitect** [Origen-SDK/o2#34]
Hi,

I would like to see pin group creation API allow the following:

~~~python
dut.add_pin_group 'mypingroup', arg1, arg2, arg3
~~~

Where arg1 could be a pin name, arg2 could be an existing pin group, and arg3 could be a regular expression.

**Comment by coreyeng** [comment]
This should all be doable. [Using single pins](https://github.com/Origen-SDK/o2/blob/pins/example/tests/pin_api_test.py#L91) is part of #21, but I haven't tried regexes.

**Comment by coreyeng** [comment]
Hi. I prototyped a basic use case [here](https://github.com/Origen-SDK/o2/blob/master/example/tests/pin_api_test.py#L805-L819). I only added it for `collections` at the moment. I want to give using [traits](https://doc.rust-lang.org/1.8.0/book/traits.html) a try and see if I can get some basic reuse going to support groups as well.

A few quick notes:

* Python doesn't support the `/.../` regex like Ruby did, so I added it. I did that mostly so I could easily tell on the Rust side what was a regex and what was a pin name. An inconsistency here though is the `/.../` won't be compiled before reaching Rust, where as using Python's `re.compile` will build the regex on the Python side, and give real feedback. Actually, I think an ill-formatted `/.../` will cause a Rust panic (will look into fixing that...).
* The regex, regardless of whether is compiled on Python or Rust, is actually run on the Rust side. In addition to assuming Rust is just faster than Python, this also saves us the trouble of converting the pin names to a Python object, running the regex on the Python side, then sending the results back to Rust to collect the pins. This does almost all the work on the Rust side.
* Since the pins are stored as a Hash, which is unordered, using a regex will return the matches in a random order. Since the order matters here, I made this deterministic by sorting the results from the regex in lexicographic order, which is how Rust sorts strings by default. There's some other crates that have a more 'natural' ordering. We can give those a try if we want.
* The crux of this was actually figuring out how to get differing classes from Python and figure out what they are on the Rust side. In retrospect, its pretty simple, but there's not much documentation on it externally. [I think we've got it though!](https://github.com/Origen-SDK/o2/blob/master/rust/origen/pyapi/src/pins/pin_container.rs#L95-L103) Basically, this matches the [Python class on Rust](https://github.com/Origen-SDK/o2/blob/master/rust/origen/pyapi/src/pins/pin_container.rs#L96) side (just using a string compare), then [runs some Python code on the object, from Rust](https://github.com/Origen-SDK/o2/blob/master/rust/origen/pyapi/src/pins/pin_container.rs#L97) (in this case, it's just running `self.getattr("pattern")`, but it could run anything.

That last bullet is the foundation for `metadata`, so I'm planning that as the next major update to pins (outside of just some cleanup). I plan to support `metadata` first, then we can see what should be extracted into its own thing. I've already kind of got [pin roles](https://github.com/Origen-SDK/o2/blob/master/rust/origen/src/core/model/pins/pin.rs#L74-L81) started and thinking `pin functions`, and `packages` will be some other additions.

Anyway, please let me know if there's any feedback thus far. Its still pretty early that changes should be straightforward.

**Comment by coreyeng** [comment]
Grouping via regexes has been added and has accompanying regressions.
